name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create Dockerfile
      run: |
        echo "FROM python:3.9-slim" > Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "COPY . /app" >> Dockerfile
        echo "CMD [\"sh\", \"-c\", \"python \$SCENARIO\"]" >> Dockerfile

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image for scenario1
      run: docker build --build-arg SCENARIO=scenario1.py -t your-dockerhub-username/scenario1 .

    - name: Build Docker image for scenario2
      run: docker build --build-arg SCENARIO=scenario2.py -t your-dockerhub-username/scenario2 .

    - name: Push Docker image for scenario1
      run: docker push your-dockerhub-username/scenario1

    - name: Push Docker image for scenario2
      run: docker push your-dockerhub-username/scenario2
