name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Dockerfile for scenario1
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "CMD [\"python\", \"scenario1.py\"]" >> Dockerfile

      - name: Build Docker image for scenario1
        run: docker build -t your-dockerhub-username/scenario1 .

      - name: Push Docker image for scenario1
        run: docker push your-dockerhub-username/scenario1

      - name: Create Dockerfile for scenario2
        run: |
          echo "FROM python:3.9-slim" > Dockerfile
          echo "WORKDIR /app" >> Dockerfile
          echo "COPY . /app" >> Dockerfile
          echo "CMD [\"python\", \"scenario2.py\"]" >> Dockerfile

      - name: Build Docker image for scenario2
        run: docker build -t your-dockerhub-username/scenario2 .

      - name: Push Docker image for scenario2
        run: docker push your-dockerhub-username/scenario2
